default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432
  username: postgres
  password: postgres

development:
  primary:
    <<: *default
    database: inventory_prod

  cable:
    <<: *default
    database: inventory_cable_prod

test:
  <<: *default
  database: inventory_test

production:
  <<: *default
  database: inventory_prod

